#define CODE_ENDS 0xef
#define COMM_STATE_BYTESHIFT_BIT 0xd8
#define COMM_STATE_BYTESHIFT_BIT1 0xd1
#define COMM_STATE_BYTESHIFT_BIT_NEXT 0xdf
#define COMM_STATE_BYTESHIFT_BIT_STOP1 0xe1
#define COMM_STATE_BYTESHIFT_BIT_STOP2 0xe8
#define COMM_STATE_BYTESHIFT_START 0xca
#define COMM_STATE_BYTE_0 0x84
#define COMM_STATE_BYTE_1 0x8b
#define COMM_STATE_BYTE_2 0x92
#define COMM_STATE_BYTE_3 0x99
#define COMM_STATE_BYTE_4 0xa0
#define COMM_STATE_BYTE_5 0xa7
#define COMM_STATE_BYTE_6 0xae
#define COMM_STATE_BYTE_7 0xb5
#define COMM_STATE_BYTE_8 0xbc
#define COMM_STATE_FINISHED 0xc3
#define COMM_STATE_MEASURE_0 0x6f
#define COMM_STATE_OFF 0x5a
#define COMM_STATE_START 0x68
#define COMM_STATE_START_BY_NCS 0x61
#define COMM_STATE_WAIT_MEASURE_0 0x76
#define COMM_STATE_WAIT_MEASURE_1 0x7d
#define comm_ret 0x28
#define loop 0xf
#define no_zero 0x27
#define no_zero_ret 0x22
#define process3samples_a 0x1c
#define process3samples_b 0x36
#define reset 0x0
#define sample0a 0xf
#define sample0b 0x29
#define sample1a 0x1b
#define sample1b 0x35
#define sample2a 0x25
#define sample2b 0x3f
#define sample2b_b 0x4f
#define sample_error0 0x4a
#define sample_error1 0x4c
