= Eszterga project ATMega328 Board Support Package

This folders contains the HAL layer for an ATMega328 implementation of the eszterga project.

Ebben a folderben található az eszterga projekt HAL rétege, ami ATMega328-on valósítja meg az összes funkciót.

== PINout nézet

Pinout view. Legend: connected interface - (used feature)PIN ID

Magyarázat: csatlakoztatott interfész - (a pin speciális funkciója, amit használunk) PIN AZONOSÍTÓ - 


         ICSP - (RESET)PC6 -|1      28|- PC5 - transistor out
DEBUG/extend   - (RXD) PD0 -|2        |- PC4 - NUMPAD row 3
DEBUG/extend   - (TXD) PD1 -|3        |- PC3 - NUMPAD row 2
         INPUT LATCH - PD2 -|         |- PC2 - NUMPAD row 1
  DIGITS PWM 1 - (OC2B)PD3 -|         |- PC1 - DIGITS latch
         Sensor2 NCS - PD4 -|         |- PC0 (ADC0) - PIN pad input
      ICSP, PowerCAP - VCC -|ATMEGA328|- GND - Connected to other GND pin
      ICSP, PowerCAP - GND -|         |- AREF - capacitor to GND
             NC-(XTAL1)PB6 -|         |- AVCC - same as VCC but additional cap to GND
             NC-(XTAL2)PB7 -|         |- PB5 (SCK)  - ISCP, SWSPI CLK, SPI ALL, Sensor ATTiny25
  DIGITS PWM 0 - (OC0B)PD5 -|         |- PB4 (MISO) - ICSP, SWSPI in, SPI BUTTONS
POWER fail 3.3V- (AIN0)PD6 -|         |- PB3 (MOSI) - ICSP, SWSPI out, SPI DIGITS, Sensor ATTiny25
POWER fail5V*0.8-(AIN1)PD7 -|         |- PB2 (SS)   - SPI (Sensor ATTiny25)
           INPUT NCS - PB0 -|14     15|- PB1 - Sensor1 NCS

== Main clock

Belső 8MHz oszcillátor elegendő a prototípushoz.
20MHz külső kvarcnak volna értelme, mert így az UART jelideje stabilabb volna.

== Timers

TIMER1 - time keeping: length of transistor strobe, period of program loop, timeout of Attiny25 SPI, currentTimeMillis, etc
TIMER0 - LED PWM -> OC0B
TIMER2 - LED PWM -> OC2B

== Interrupts, ATOMIC blocks

TIMER1 ovf: increment timekeeping counter
getCurrentTimeMillis - read out timekeeping counter+TCNT1
SPI input? SW SPI could also be used!


== Gombok és LED-ek további jelei

 * DIGITS latch: az összes kimenet vezérlő shift regiszternek a latch-ét erre kell kötni
 * INPUT latch: az összes bemenetet vezérlő shift regiszternek a latch-ét erre kell kötni
 * DIGITS PWM 0: Minden második digit OE-jét ide kell kötni
 * DIGITS PWM 1: Minden második digit OE-jét ide kell kötni (így két fázira tudjuk bontani a PWM-et, tehát nem egyszerre ég az összes LED)

=== Kimeneti Shift reg bekötése

Chip például: 74HC595-SMD adatlap: http://www.ti.com/lit/ds/scls041i/scls041i.pdf

 * /OE - DIGITS PWM 0 - (OC0B)PD5 vagy DIGITS PWM 1 - (OC2B)PD3
 * SRCLK - PB5 (SCK)
 * SER - PB3 (MOSI)
 * RCLK - PC1 - DIGITS latch
 * Minden jel kimenet a mikrovezérlő oldalán, és lehet védeni 1kOhm ellenállással például
 * SRCLR - pullup 5V-ra pl 4.7kOhm

=== Bemeneti Shift reg bekötése

Chip például: 74HCT166-SMD adatlap: http://www.ti.com/lit/ds/symlink/cd74hc166.pdf

 * D0-D7 8 gomb bemenet. Minden bemenet legyen GND-re húzva pl 10kOhm-mal, és a benyomott gomb húzza 5V-ra (tehát magas aktív bemenet)
 * GND, VCC értelemszerű
 * /CE - GND-re pl 10kOhm-mal
 * CP - PB5 (SCK)
 * Q7 - az utolsót egy buffer-en keresztül a uC-re: PB4 (MISO) - a többit felfűzni úgy, hogy a következő DS-ébe van kötve ez a kimenet.
 * /PE - INPUT LATCH - (PCINT18)PD2
 * /MR - +5V ellenálláson keresztül - pl 10kOhm
 * DS - bemenet, a sorba kötött előző Shift regiszter Q7 portjára kell kötni

Buffer szerepe és bekötése:

 * A buffer szerepe, hogy a MISO vonal vezéreletlen legyen, ha az ATMega úgy akarja. Ezért a buffer vezérlőjét úgy kell bekötni, hogy magától inaktív legyen.
 * Pl: 74HC125 SMD adatlap: https://www.hestore.hu/prod_getfile.php?id=8883
 * 1A: SHR Q7-re
 * /1OE: ATmega328 (INPUT NCS) PB0, plusz 10kOhm felhúzó ellenállás
 * 1Y: ATMega328 (MISO) PB4

A buffer többi 3 komponense nem használt. A bemeneteket érdemes magasba húzni.

=== PINPAD bekötése

 * Ellenállásháló kimenete PC0(ADC0)-ra! (0-5V tartományon lehet a bemenet értéke, tehát a hálót is 5V-tal kell táplálni, szerintem a legjobb azzal, ami az AVCC-re van kötve)
 * AVCC szűrt 5V-ra!
 * AREF kapacitással a GND-re!

== Power fail detector

Így kell bekötni:

 * PD6(AIN0) 3.3V referencia: 3.3V stabilizátorral készített 3.3V-os bemeneti referencia jel.
 * PD7(AIN1) 5V*0,825: a külső tápot osztjuk két ellenállással úgy, hogy 0,825-szorosát mérjük. Ha a táp 4V-ra esik, akkor ez az érték éppen 3.3V lesz, tehát a komparátor jelezni fog. (az osztó lehet egy potméter, és akkor hangolható lesz a kikapcsolási feszültség)

Így működik:

 * A komparátor áramkör a 3.3V referenciát és a külső táp osztott értékét méri egymáshoz. Amikor a külső táp feszültsége pl 4V alá esik, akkor interrupttal azonnal jelez a főprogramnak!
 * Ekkor a belső tápáramkör kondenzátora még legalább 4V-ra fel van tölte: ennek az energiája elegendő lesz az állapotmentéshez - úgy mérezezzük be ezt a kondenzátort
 * A jelzésére a főprogram minden fogyasztót leállít - hogy keveset fogyasszon, legyen egy kis ideje elmenteni az állapotát.
 * Az állapotát elmenti a csipbe épített EEPROM-ba.
 * A külső fogyasztókat viszont bekapcsolja, hogy mielőbb kisüljenek a külső táp kondenzátorai.
 * Miután a mentés megtörtént a főprogram bekapcsol egy fogyasztót, ami a belső kondenzátort is lemeríti. Például van egy státusz LED, amit kigyújt, vagy az egyik lába GND-re van kötve ellenálláson keresztül.
 * A tápláló kondenzátor lemerül, és a csip kikapcsol. Brown Out Detectort érdemes bekapcsolni a csipen, hogy még azelőtt kikapcsoljon, mielőtt elkezdene esetleg hibásan működni.
 * Ha a csip leállása nélkül visszajön a táp (gyors kapcsolgatás), vagy csak vaklárma volt (tranziens alacsony feszültség valami hibából adódóan), akkor egy idő után folytatja a program a futását.


== ICSP

ICSP header konfigurációjú 2x3 pines csatlakozóra kell kötni, hogy standard programozóval, vagy pickit2-vel lehessen programozni.

Minden egyéb funkciót egy 4.7k ellenálláson kerresztül kell rákötni, hogy az ICSP "felül tudja bírálni". A jelek a 4.7k-n gond nélkül átmennek.

== SPI

A Hardweres SPI-t arra használjuk, hogy a Quad dekóder adatát beolvassuk.

 * SS -> 4.7k pull down to GND szükséges, más nem kell.
 * SCK -> 4.7k-n keresztül a SHR-ekre és a két Attiny25 CLK-jára kell kötni
 * MOSI -> 4.7k-n keresztül a kimeneti SHR-ekre kell kötni, és az Attiny25 DO-jára
 * MISO -> 4.7k-n keresztül a bemeneti SHR-ek kimenetére kell kötni

== ATTiny sensor

Sensor1 NCS - Negated Chip Select: a szenzor 1 (Attiny25)-nek jelzi, hogy küldheti az adatot
Sensor2 NCS - Negated Chip Select: a szenzor 2 (Attiny25)-nek jelzi, hogy küldheti az adatot

=== Első szenzor bekötése

 * GND, VCC értelemszerűen (kapacitás kell rá)
 * /RESET - VCC-re 10kOhm-mal
 * T25 PB0(INPUT_A)                - QuadA a jeladóból
 * T25 PB1(NCS)                    - MEGA328 PB1 - Sensor1 NCS - soros 10kOhm lehet
 * T25 PB2(INPUT_B)                - QuadB a jeladóból
 * T25 PB3(SPI_DATA)               - MEGA328 PB3 (MOSI) - Kisértékű ellenálláson keresztül, pl 500 Ohm (max 10mA-re korlátoz)
 * T25 PB4(SPI_CLK)                - MEGA328 PB5 (SCK) - Kisértékű ellenálláson keresztül, pl 500 Ohm (max 10mA-re korlátoz)
                                   - MEGA328 SS -> 4.7k pull down to GND szükséges, különben nem működik


=== Második szenzor bekötése

 * GND, VCC értelemszerűen (kapacitás kell rá)
 * /RESET - VCC-re 10kOhm-mal
 * T25 PB0(INPUT_A)                - QuadA a jeladóból
 * T25 PB1(NCS)                    - MEGA328 PD4 - Sensor2 NCS - soros 10kOhm lehet
 * T25 PB2(INPUT_B)                - QuadB a jeladóból
 * T25 PB3(SPI_DATA)               - MEGA328 PB3 (MOSI) - Kisértékű ellenálláson keresztül, pl 500 Ohm (max 10mA-re korlátoz)
 * T25 PB4(SPI_CLK)                - MEGA328 PB5 (SCK) - Kisértékű ellenálláson keresztül, pl 500 Ohm (max 10mA-re korlátoz)
                                   - MEGA328 SS -> 4.7k pull down to GND szükséges, különben nem működik

== transistor out

Ez vezérli a lineáris motort, ami reteszeli a gépet. Optocsatolón keresztül hajt egy tranzisztort. TODO magas, vagy alacsony aktív?

== DEBUG/extend

UART ki/bemenet - log üzenetek kiíratása hibakereséshez. Serial adapterrel PC-re köthető, ha kell. További funkciókkal lehet később a serialon keresztül összekötni a gépet.

== NC - nincs bekötve

Ezekre semmit nem kell kötni, a belső felhúzó ellenállással kb 40kOhm-mal magasba lesznek húzva.
Not connected: internal pullup will be activated in the chip for these pins.

