
all:
	make -C blinky
	make -C gui_atmega328
	make -C emscripten
	make -C quad_decoder_attiny25_custom
	make -C test/quad_signalGenerator

clean:
	make -C blinky clean
	make -C gui_atmega328 clean
	make -C emscripten clean
	make -C quad_decoder_attiny25_custom clean
	make -C test/quad_signalGenerator clean

