/**
 * Első multithreading példa, ami működik.
 */
#include <stdint.h>
#include <stddef.h>
#include <avr/io.h>
#include <string.h>
#include <avr/interrupt.h>

#include "debug.h"
#include "multithreading.h"

void threadFun();

static void wait1s();

void main()
{
	init_uart();
	thread_t otherThread;
	thread_system_init();
	thread_create(&otherThread, threadFun, 1024);
	while(1)
	{
		// Turn LED on
		DDRE|=_BV(4);
		PORTE|=_BV(4);
		// WAIT
		wait1s();
		sendByte('B');

		thread_switch(&otherThread);
	}
}


void threadFun()
{
	while(1)
	{
		sendByte('F');
		// Turn LED off
		DDRE|=_BV(4);
		PORTE&=~_BV(4);
		// WAIT
		wait1s();
		thread_switch(thread_get_main());
	}
	
}
static void wait1s()
{
// Uses call clobbered registers so it is safe to not save them.

// Generated by delay loop calculator
// at http://www.bretmulvey.com/avrdelay.html
//
// Delay 20 000 000 cycles
// 1s at 20.0 MHz

asm volatile (
    "    ldi  r18, 102"	"\n"
    "    ldi  r19, 118"	"\n"
    "    ldi  r20, 194"	"\n"
    "1:  dec  r20"	"\n"
    "    brne 1b"	"\n"
    "    dec  r19"	"\n"
    "    brne 1b"	"\n"
    "    dec  r18"	"\n"
    "    brne 1b"	"\n"
);

}

