extern bool AVR_rjmp(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_reti(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_in(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t d);
extern bool AVR_mov(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_add(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_lsr(AVR_simulator_t * ctx, uint32_t pc, uint8_t d);
extern bool AVR_eor(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_or(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_ijmp(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_sbic(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t b);
extern bool AVR_sbrs(AVR_simulator_t * ctx, uint32_t pc, uint8_t b, uint8_t r);
extern bool AVR_sbrc(AVR_simulator_t * ctx, uint32_t pc, uint8_t b, uint8_t r);
extern bool AVR_subi(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_out(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t r);
extern bool AVR_sbiw(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_adiw(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_ldi(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_cbi(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t b);
extern bool AVR_andi(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_sbi(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t b);
extern bool AVR_swap(AVR_simulator_t * ctx, uint32_t pc, uint8_t d);
extern bool AVR_rcall(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_cli(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_sei(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_sbis(AVR_simulator_t * ctx, uint32_t pc, uint8_t A, uint8_t b);
extern bool AVR_movw(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_ret(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_sub(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_sbc(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_sbci(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_cp(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_cpc(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_brsh(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_adc(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_and(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t r);
extern bool AVR_brne(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_breq(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_nop(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_brge(AVR_simulator_t * ctx, uint32_t pc, uint32_t k);
extern bool AVR_inc(AVR_simulator_t * ctx, uint32_t pc, uint8_t d);
extern bool AVR_dec(AVR_simulator_t * ctx, uint32_t pc, uint8_t d);
extern bool AVR_cpi(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
extern bool AVR_lpmr0(AVR_simulator_t * ctx, uint32_t pc);
extern bool AVR_lpm(AVR_simulator_t * ctx, uint32_t pc, uint8_t d, uint8_t i);
extern bool AVR_sbr(AVR_simulator_t * ctx, uint32_t pc, uint8_t K, uint8_t d);
